#!/usr/bin/env python3
"""Generate deterministic release artefacts from data/index/*.jsonl.

Emits three files at the repo root:

  - NOTICE.md         human-readable attribution roll-up.
  - CITATION.cff      Citation File Format 1.2.0.
  - datapackage.json  Frictionless Data Package manifest.

The script is fully deterministic: same indexes in, byte-identical files out.
No datetime.now(), no random ordering, no UUIDs. `released_at` is derived from
the most recent `provenance.acquired_at` in entries.jsonl so the timestamp
reflects the corpus state, not the time the script happened to run.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCES_PATH = REPO_ROOT / "data" / "index" / "sources.jsonl"
ENTRIES_PATH = REPO_ROOT / "data" / "index" / "entries.jsonl"
RECIPE_PATH = REPO_ROOT / "scripts" / "release_recipe.json"
NOTICE_PATH = REPO_ROOT / "NOTICE.md"
CITATION_PATH = REPO_ROOT / "CITATION.cff"
DATAPACKAGE_PATH = REPO_ROOT / "datapackage.json"


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise SystemExit(f"{path}: file does not exist")
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                rows.append(json.loads(stripped))
            except json.JSONDecodeError as exc:
                raise SystemExit(f"{path}:{line_number}: invalid JSON: {exc}") from exc
    return rows


def _load_recipe(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"{path}: file does not exist")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path}: invalid JSON: {exc}") from exc


def _derive_released_at(entries: list[dict[str, Any]]) -> str:
    acquired = [
        entry["provenance"]["acquired_at"]
        for entry in entries
        if entry.get("provenance") and entry["provenance"].get("acquired_at")
    ]
    if not acquired:
        raise SystemExit("no provenance.acquired_at values found in entries.jsonl")
    return max(acquired)


def _released_date(released_at: str) -> str:
    # The schema enforces RFC 3339 date-time, so the first 10 chars are YYYY-MM-DD.
    return released_at[:10]


def _license_breakdown(entries: list[dict[str, Any]]) -> dict[str, int]:
    counts = Counter(entry["rights"]["license_expression"] for entry in entries)
    return {key: counts[key] for key in sorted(counts)}


def _institution_breakdown(entries: list[dict[str, Any]]) -> dict[str, int]:
    counts = Counter(
        entry["holding_institution"]
        for entry in entries
        if entry.get("holding_institution")
    )
    return {key: counts[key] for key in sorted(counts)}


def _byte_count(entries: list[dict[str, Any]]) -> int:
    total = 0
    for entry in entries:
        for file_obj in entry["files"]:
            byte_size = file_obj.get("bytes")
            if isinstance(byte_size, int):
                total += byte_size
    return total


def _attribution_entries(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    selected = [
        entry for entry in entries if entry["rights"].get("attribution_required") is True
    ]
    return sorted(selected, key=lambda entry: entry["entry_id"])


def build_notice(
    entries: list[dict[str, Any]],
    recipe: dict[str, Any],
    released_at: str,
) -> str:
    license_names = recipe.get("license_names", {})
    license_urls = recipe.get("license_urls", {})

    lines: list[str] = []
    lines.append("# NOTICE")
    lines.append("")
    lines.append(
        "This file is generated by `scripts/generate_release_artifacts.py` from "
        "`data/index/entries.jsonl`. Do not edit by hand."
    )
    lines.append("")
    lines.append(
        "Repository-authored metadata is dedicated to the public domain under "
        "CC0 1.0 Universal. See [`LICENSE`](LICENSE) and [`LICENSE.md`](LICENSE.md) "
        "for the full compound-licensing policy."
    )
    lines.append("")
    lines.append(
        "Scan files carry per-entry rights. The entries listed below have "
        "`rights.attribution_required: true` in the index. Anyone redistributing or "
        "reusing these scans must keep the listed credit and link to the source page "
        "on which the rights claim was verified."
    )
    lines.append("")
    lines.append(f"- Corpus release: `{recipe['version']}`")
    lines.append(f"- Released at: `{released_at}`")
    lines.append("")
    lines.append("## Attribution-required entries")
    lines.append("")

    required = _attribution_entries(entries)
    if not required:
        lines.append("_No entries in this release require attribution._")
        lines.append("")
    else:
        for entry in required:
            rights = entry["rights"]
            license_expr = rights["license_expression"]
            license_name = license_names.get(license_expr, license_expr)
            license_url = license_urls.get(license_expr)

            lines.append(f"### {entry['title']}")
            lines.append("")
            lines.append(f"- Entry: `{entry['entry_id']}`")
            if license_url:
                lines.append(
                    f"- License: [{license_name} ({license_expr})]({license_url})"
                )
            else:
                lines.append(f"- License: {license_name} ({license_expr})")
            lines.append(f"- Licensor: {rights['attribution_text']}")
            lines.append(f"- Source page: <{rights['attribution_url']}>")

            file_url = entry["files"][0].get("source_url") if entry.get("files") else None
            if file_url and file_url != rights["attribution_url"]:
                lines.append(f"- Scan file URL: <{file_url}>")

            holding = entry.get("holding_institution")
            if holding:
                shelf = entry.get("holding_shelfmark")
                if shelf:
                    lines.append(f"- Holding institution: {holding} ({shelf})")
                else:
                    lines.append(f"- Holding institution: {holding}")
            lines.append("")

    lines.append("## Full per-entry rights")
    lines.append("")
    lines.append(
        "Every entry, attribution-required or not, ships with its rights record in "
        "[`data/index/entries.jsonl`](data/index/entries.jsonl). Consumers that need "
        "machine-readable rights metadata should read that file directly; the "
        "manifest at [`datapackage.json`](datapackage.json) summarises the license "
        "breakdown."
    )
    lines.append("")
    return "\n".join(lines)


def _yaml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if value is None:
        return "null"
    return f'"{_yaml_escape(str(value))}"'


def build_citation(
    entries: list[dict[str, Any]],
    sources: list[dict[str, Any]],
    recipe: dict[str, Any],
    released_at: str,
) -> str:
    record_count = len(entries)
    source_count = len({entry["source_id"] for entry in entries})
    license_counts = _license_breakdown(entries)
    breakdown_summary = ", ".join(
        f"{count} {license_id}" for license_id, count in license_counts.items()
    )

    abstract = (
        f"{recipe['description']} Release {recipe['version']} contains "
        f"{record_count} scan entries drawn from {source_count} verified sources "
        f"({breakdown_summary})."
    )

    lines: list[str] = []
    lines.append("# Generated by scripts/generate_release_artifacts.py. Do not edit by hand.")
    lines.append("cff-version: 1.2.0")
    lines.append(f"message: {_yaml_scalar('Please cite this dataset using the metadata below.')}")
    lines.append("type: dataset")
    lines.append(f"title: {_yaml_scalar(recipe['title'])}")
    lines.append(f"abstract: {_yaml_scalar(abstract)}")
    lines.append("authors:")
    for author in recipe.get("authors", []):
        lines.append(f"  - name: {_yaml_scalar(author['name'])}")
    lines.append(f"version: {_yaml_scalar(recipe['version'])}")
    lines.append(f"date-released: {_yaml_scalar(_released_date(released_at))}")
    lines.append(f"repository-code: {_yaml_scalar(recipe['repository_code'])}")
    lines.append(f"url: {_yaml_scalar(recipe['homepage'])}")
    lines.append(f"license: {_yaml_scalar(recipe['metadata_license']['spdx'])}")
    lines.append("keywords:")
    for keyword in sorted(recipe.get("keywords", [])):
        lines.append(f"  - {_yaml_scalar(keyword)}")
    return "\n".join(lines) + "\n"


def build_datapackage(
    entries: list[dict[str, Any]],
    sources: list[dict[str, Any]],
    recipe: dict[str, Any],
    released_at: str,
) -> dict[str, Any]:
    license_names = recipe.get("license_names", {})
    license_urls = recipe.get("license_urls", {})
    license_counts = _license_breakdown(entries)
    institutions = _institution_breakdown(entries)

    source_status_counts = Counter(source.get("status") for source in sources)
    source_status_breakdown = {
        key: source_status_counts[key]
        for key in sorted(source_status_counts)
        if key is not None
    }

    license_listings: list[dict[str, Any]] = []
    license_listings.append(
        {
            "name": recipe["metadata_license"]["spdx"],
            "path": recipe["metadata_license"]["url"],
            "title": license_names.get(
                recipe["metadata_license"]["spdx"],
                recipe["metadata_license"]["spdx"],
            ),
            "scope": "metadata",
        }
    )
    for license_id in sorted(license_counts):
        entry: dict[str, Any] = {
            "name": license_id,
            "title": license_names.get(license_id, license_id),
            "scope": "scans",
        }
        url = license_urls.get(license_id)
        if url:
            entry["path"] = url
        license_listings.append(entry)

    resources: list[dict[str, Any]] = []
    for name in sorted(recipe["resources"]):
        spec = recipe["resources"][name]
        resource_path = REPO_ROOT / spec["path"]
        record_count: int | None = None
        byte_count: int | None = None
        if resource_path.exists():
            byte_count = resource_path.stat().st_size
            with resource_path.open("r", encoding="utf-8") as handle:
                record_count = sum(1 for line in handle if line.strip())
        resource: dict[str, Any] = {
            "name": name,
            "path": spec["path"],
            "profile": "data-resource",
            "format": spec["format"],
            "mediatype": spec["mediatype"],
            "encoding": spec["encoding"],
            "description": spec["description"],
        }
        if record_count is not None:
            resource["record_count"] = record_count
        if byte_count is not None:
            resource["bytes"] = byte_count
        if name == "entries":
            resource["schema"] = recipe["schema_urls"]["entry"]
        elif name == "sources":
            resource["schema"] = recipe["schema_urls"]["source"]
        resources.append(resource)

    package: dict[str, Any] = {
        "profile": "data-package",
        "name": recipe["name"],
        "title": recipe["title"],
        "description": recipe["description"],
        "version": recipe["version"],
        "released_at": released_at,
        "homepage": recipe["homepage"],
        "keywords": sorted(recipe.get("keywords", [])),
        "contributors": [
            {"title": author["name"], "role": author.get("role", "author")}
            for author in recipe.get("authors", [])
        ],
        "licenses": license_listings,
        "schemas": {
            "entry": recipe["schema_urls"]["entry"],
            "source": recipe["schema_urls"]["source"],
        },
        "stats": {
            "record_count": len(entries),
            "source_count": len({entry["source_id"] for entry in entries}),
            "source_record_count": len(sources),
            "source_status_breakdown": source_status_breakdown,
            "byte_count": _byte_count(entries),
            "attribution_required_count": sum(
                1 for entry in entries
                if entry["rights"].get("attribution_required") is True
            ),
            "license_breakdown": license_counts,
            "institution_breakdown": institutions,
        },
        "resources": resources,
    }
    return package


def _write_text(path: Path, text: str) -> None:
    if not text.endswith("\n"):
        text = text + "\n"
    path.write_text(text, encoding="utf-8")


def _write_json(path: Path, data: dict[str, Any]) -> None:
    serialized = json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True)
    _write_text(path, serialized)


def generate(
    sources_path: Path = SOURCES_PATH,
    entries_path: Path = ENTRIES_PATH,
    recipe_path: Path = RECIPE_PATH,
    notice_path: Path = NOTICE_PATH,
    citation_path: Path = CITATION_PATH,
    datapackage_path: Path = DATAPACKAGE_PATH,
) -> dict[str, Path]:
    sources = _load_jsonl(sources_path)
    entries = _load_jsonl(entries_path)
    recipe = _load_recipe(recipe_path)
    released_at = _derive_released_at(entries)

    notice = build_notice(entries, recipe, released_at)
    citation = build_citation(entries, sources, recipe, released_at)
    datapackage = build_datapackage(entries, sources, recipe, released_at)

    _write_text(notice_path, notice)
    _write_text(citation_path, citation)
    _write_json(datapackage_path, datapackage)

    return {
        "notice": notice_path,
        "citation": citation_path,
        "datapackage": datapackage_path,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sources", type=Path, default=SOURCES_PATH)
    parser.add_argument("--entries", type=Path, default=ENTRIES_PATH)
    parser.add_argument("--recipe", type=Path, default=RECIPE_PATH)
    parser.add_argument("--notice", type=Path, default=NOTICE_PATH)
    parser.add_argument("--citation", type=Path, default=CITATION_PATH)
    parser.add_argument("--datapackage", type=Path, default=DATAPACKAGE_PATH)
    args = parser.parse_args()

    written = generate(
        sources_path=args.sources,
        entries_path=args.entries,
        recipe_path=args.recipe,
        notice_path=args.notice,
        citation_path=args.citation,
        datapackage_path=args.datapackage,
    )

    for label, path in written.items():
        try:
            display = path.relative_to(REPO_ROOT)
        except ValueError:
            display = path
        print(f"wrote {label}: {display}")


if __name__ == "__main__":
    main()
